In [64]:
import geopandas as gpd
import pandas as pd
sal= pd.read_csv('../pop_pred_final.csv')
phm=pd.read_csv('../../PHARMACIES_places_full_results.csv')

In [75]:
salpoint=gpd.read_file('../../2011_census/2011_Census/2011_ea_sal_centroids_kzn_gp.dbf')
salpoly=gpd.read_file('../../2011_census/2011_Census/ea_sal_kzn_gp.dbf')

In [67]:
pharm_gdf = gpd.GeoDataFrame(
    phm,
    geometry=gpd.points_from_xy(phm['lng'], phm['lat']),
    crs="EPSG:4326"  # WGS84
)
pharm_gdf = pharm_gdf.to_crs(salpoly.crs)

In [68]:
pharm_with_sal = gpd.sjoin(
    pharm_gdf,
    salpoly[['EA_CODE', 'EA_GTYPE', 'geometry']],
    how='left',
    predicate='within'
)

In [69]:
pharm_with_sal.head()

,raw_row_id,PHARMACY_ID,PRACTICE_NUM,PRACTICE_NAME,ADDRESS,CITY,PROVINCE,PHONE,query_string,http_status,...,matched_address,lat,lng,types,raw_error,needs_review,geometry,index_right,EA_CODE,EA_GTYPE
0,NaN,1461,100943,Dis-Chem Olympus Pharmacy,"Shop No 1, Dis-Chem Shopping Centre, Corner Ha...",NaN,Gauteng,129910084.0,"Dis-Chem Olympus Pharmacy, Shop No 1, Dis-Chem...",200,...,"Shop 116, 108 Haymeadow Cres, Faerie Glen, Pre...",-25.796377,28.321911,"drugstore, establishment, furniture_store, hea...",NaN,False,POINT (28.32191 -25.79638),33381.0,79911459.0,Urban
1,NaN,1462,100943,Dis-Chem Olympus Pharmacy,"Dis-Chem Centre, Faerie Glen, Pretoria",NaN,Gauteng,NaN,"Dis-Chem Olympus Pharmacy, Dis-Chem Centre, Fa...",200,...,"Shop 116, 108 Haymeadow Cres, Faerie Glen, Pre...",-25.796377,28.321911,"drugstore, establishment, furniture_store, hea...",NaN,False,POINT (28.32191 -25.79638),33381.0,79911459.0,Urban
2,NaN,3139,1013882,Tlangelani Pharmacy Tembisa,"Shop No9, Tembisa Mega Mart, Corner Olifantsfo...",NaN,Gauteng,113160001.0,"Tlangelani Pharmacy Tembisa, Shop No9, Tembisa...",200,...,"6 Olifantsfontein Rd, Thembisa, Johannesburg, ...",-25.964747,28.211362,"establishment, health, pharmacy, point_of_inte...",NaN,False,POINT (28.21136 -25.96475),19360.0,79715176.0,Urban
3,NaN,3140,1013882,Tlangelani Pharmacy Tembisa,"Shop 9, Tembisa Mega-Mart, Tswelopele, Tembisa",NaN,Gauteng,NaN,"Tlangelani Pharmacy Tembisa, Shop 9, Tembisa M...",200,...,"6 Olifantsfontein Rd, Thembisa, Johannesburg, ...",-25.964747,28.211362,"establishment, health, pharmacy, point_of_inte...",NaN,False,POINT (28.21136 -25.96475),19360.0,79715176.0,Urban
4,NaN,350,1015079,Clicks Pharmacy - Faerie Glen Hyper,"Pick `n Pay Hypermarket, Faerie Glen, Pretoria",NaN,Gauteng,NaN,"Clicks Pharmacy - Faerie Glen Hyper, Pick `n P...",200,...,"Cnr Atterbury Rd &, Pick n Pay Hyper, Selikats...",-25.783818,28.304890,"establishment, health, pharmacy, point_of_inte...",NaN,False,POINT (28.30489 -25.78382),33353.0,79911713.0,Urban

In [50]:
# sal=sal.merge(
#     salpoint, 
#     on="EA_CODE",
# )

C:\Users\kalmanj\AppData\Local\Temp\ipykernel_27532\3562391804.py:1: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  sal=sal.merge(

In [60]:
sal

,WardID,EA_CODE,sal2011_pop,ward2023_pop,EA_GTYPE,EA_TYPE,econ_status,houses2011,Black_Afri,White,...,Other,area_km2,sal_dense,log_density,ward2011_sum,share2011,dasym_weight,sal2023_est,growth_rate,catchment
0,52103007,50310272,559.0,5886.912582,Traditional,Traditional residential,Non_Wealthy,131.0,558.0,0.0,...,0.0,6.072531,92.053872,4.533179,7387.0,0.075673,0.066565,391.862892,-0.029169,8.0
1,52103007,50310271,713.0,5886.912582,Traditional,Traditional residential,Non_Wealthy,167.0,713.0,0.0,...,0.0,3.900819,182.782137,5.213751,7387.0,0.096521,0.097650,574.856332,-0.017787,8.0
2,52103007,50310262,443.0,5886.912582,Traditional,Traditional residential,Non_Wealthy,135.0,443.0,0.0,...,0.0,1.926623,229.935961,5.442140,7387.0,0.059970,0.063329,372.814653,-0.014271,8.0
3,52103007,50310266,743.0,5886.912582,Traditional,Traditional residential,Non_Wealthy,154.0,740.0,0.0,...,1.0,1.706669,435.350859,6.078447,7387.0,0.100582,0.118635,698.394683,-0.005146,8.0
4,52103006,50310265,339.0,7902.254373,Traditional,Traditional residential,Non_Wealthy,92.0,339.0,0.0,...,0.0,4.054491,83.610997,4.438064,8923.0,0.037992,0.034488,272.535703,-0.018022,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38375,59500015,59912265,0.0,44864.912304,Urban,Vacant,NaN,0.0,NaN,NaN,...,NaN,0.515945,0.000000,0.000000,33583.0,0.000000,0.000000,0.000000,NaN,3.2
38376,59500103,59914036,540.0,39704.126380,Urban,Small holdings,Wealthy,180.0,NaN,NaN,...,NaN,4.055769,133.143671,4.898911,33248.0,0.016242,0.011946,474.302535,-0.010752,3.2
38377,59500049,59915062,0.0,52055.310791,Urban,Formal residential,NaN,0.0,NaN,NaN,...,NaN,0.021079,0.000000,0.000000,41652.0,0.000000,0.000000,0.000000,NaN,3.2
38378,59500063,59911731,78.0,41787.592756,Urban,Informal residential,Non_Wealthy,26.0,NaN,NaN,...,NaN,0.540035,144.435173,4.979730,36133.0,0.002159,0.001395,58.281108,-0.023993,3.2
38379,59500018,59912077,0.0,31476.750052,Urban,Vacant,NaN,0.0,NaN,NaN,...,NaN,0.180507,0.000000,0.000000,39518.0,0.000000,0.000000,0.000000,NaN,3.2

In [72]:
def assign_catchment(row):
    if row['EA_GTYPE'] == 'Urban':
        return 2 * 1609.34
    elif row['EA_GTYPE'] == 'Traditional':
        return 5 * 1609.34
    else:
        return 15 *1609.34

sal['catchment'] = sal.apply(assign_catchment, axis=1)
pharm_with_sal['catchment'] = pharm_with_sal.apply(assign_catchment, axis=1)

In [81]:
import osmnx as ox

# bounds = [minx, miny, maxx, maxy]
minx, miny, maxx, maxy = salpoly.total_bounds

bbox = (miny, maxy, minx, maxx)  # (south, north, west, east)

G = ox.graph_from_bbox(
    bbox,
    network_type='drive'
)

C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\osmnx\_overpass.py:271: UserWarning: This area is 16,599 times your configured Overpass max query area size. It will automatically be divided up into multiple sub-queries accordingly. This may take a long time.
  multi_poly_proj = utils_geo._consolidate_subdivide_geometry(poly_proj)
C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'overpass-api.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'overpass-api.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'overpass-api.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'overpass-api.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'overpass-api.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'overpass-api.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'overpass-api.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'overpass-api.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'overpass-api.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'overpass-api.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\kalmanj\AppData\Local\anaconda3\envs\urbanspatial\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'overpass-api.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

KeyboardInterrupt:

In [80]:
ox.settings.requests_kwargs = {"verify": False}

In [ ]:
sal['node'] = ox.nearest_nodes(G, salpoly.geometry.x, salpoly.geometry.y)
pharm_with_sal['node'] = ox.nearest_nodes(G, pharm_with_sal.geometry.x, pharm_with_sal.geometry.y)

In [ ]:
from tqdm import tqdm
###Finding all population within catchment distance of sal type
Rj_list = []

for idx, pharm in tqdm(pharm_gdf.iterrows(), total=len(pharm_gdf)):
    lengths = nx.single_source_dijkstra_path_length(
        G,
        pharm['node'],
        cutoff=pharm['catchment'],
        weight='length'
    )
    
    reachable_nodes = set(lengths.keys())
    
    # find population points whose nodes are reachable
    nearby_pop = pop_gdf[sal['node'].isin(reachable_nodes)]
    
    total_pop = nearby_pop['sal2023_est'].sum()

    ##over 1 because the higher the pop around a pharm. the weaker the supply 
 
    if total_pop > 0:
        Rj = 1 / total_pop
    else:
        Rj = 0
    
    Rj_list.append(Rj)

pharm_gdf['Rj'] = Rj_list

In [ ]:
Ai_list = []

###measuring the # of pharmacies within catchment node of SAL 

for idx, pop in tqdm(sal.iterrows(), total=len(salpoint)):
    lengths = nx.single_source_dijkstra_path_length(
        G,
        pop['node'],
        cutoff=pop['catchment'],
        weight='length'
    )
    
    reachable_nodes = set(lengths.keys())
    
    nearby_pharm = pharm_gdf[pharm_gdf['node'].isin(reachable_nodes)]

    
###now were summing all supply ratios of sal node to measure demand    
  
    Ai = nearby_pharm['Rj'].sum()
    
    Ai_list.append(Ai)

sal['Ai'] = Ai_list

In [ ]:

#higher the Ai, the better the access  
pop_gdf[['tract_id', 'Ai']].head()